version: '3'

services:

  rabbitmq:
    image: vieirajonathan/rabbitmq
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672" 
    labels:
      NAME: "rabbitmq"
#    volumes:
#      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
#      - ./definitions.json:/opt/definitions.json

  mysql:
    image: vieirajonathan/mysql
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#    volumes:
#      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

  python:
#    build: ./hello-python/ 
#    volumes:
#      - .:/code
    image: vieirajonathan/hello-python
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_QUEUE: "hello"
    links: [rabbitmq]

  node:
#    build: ./hello-node/ 
#    volumes:
#      - .:/code
    image: vieirajonathan/hello-node
    depends_on:
      - rabbitmq
      - mysql
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_QUEUE: "hello"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      MYSQL_HOST: mysql
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "example"
      MYSQL_DB: "hello"
      WAIT_HOSTS: rabbitmq:5672, mysql:3306
    links: [rabbitmq,mysql]


